### PR TITLE
Revert "Add Local Rate Limit Filter (#20)"

### PR DESCRIPTION
**Pull request by bianpengyuan**
This reverts commit 876d9789bdd95382305801c02682cb295871c42f.

It is actually impossible to implement local rate limiting with current Wasm ABI, as there is only get/set interface and global shared data cannot be operated atomically like refill or subtract by 1. We should remove it until we have a correct implementation.

Signed-off-by: Pengyuan Bian <bianpengyuan@google.com>

### CODE REVIEW

**Comment by mandarjog** [comment]
Can we have a bounded worst case with these blond writes?
If you are unsing 1 worker thread you are fine. What is the worst case with 2 workers?

**Comment by bianpengyuan** [comment]
Worst case, assuming the rate limit user specifies is `x` and worker number is `y`, the actual rate limit could be in range `[x/y, x*y]`, as both refill and subtract can be racey.

**Comment by bianpengyuan** [comment]
@mandarjog ptal, thanks!

**Review by mandarjog — APPROVED** [review]
Lgtm

**Pull request merged**
