### PR TITLE
Add Local Rate Limit Filter

### PR DESCRIPTION
**Pull request by gargnupur**

### CODE REVIEW

**Comment by gargnupur** [comment]
This is still work-in-progress.. will ping when it's ready for review.

**Comment by bianpengyuan** [comment]
I think we'd want something much simpler, probably just the following:
```protobuf
message LocalRateLimitConfig {
  message QuotaConfig {
    google.protobuf.duration interval = 1;
    int max_requests = 2;
  }
  repeated QuotaConfig quota_configs = 1;
}
```

Instead of rich configurability, user should just customize the plugin. wdyt? @mandarjog @kyessenov

**Review by bianpengyuan — COMMENTED** [review]
I guess `test/local_rate_limit_plugin/tmp ` is a junk file which needs to be removed?

**Review by bianpengyuan — APPROVED** [review]
Thanks! Let's get this in and I will refine this afterwards.

**Pull request merged**
